@echo off
echo Adding modified files to git...
git add .
echo Committing changes...
git commit -m "Fix Vercel serverless deployment: export request handler and add vercel.json"
echo Setting remote repository URL...
git remote set-url origin https://github.com/ianuj-yadav/Crm-Project.git 2>nul || git remote add origin https://github.com/ianuj-yadav/Crm-Project.git
git branch -M main
echo Pushing to https://github.com/ianuj-yadav/Crm-Project.git...
git push -u origin main
echo Done!
pause
